# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False)),
                ('template_description', models.CharField(blank=True, max_length=255)),
                ('created_from', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Document')),
            ],
            options={
                'ordering': ('document_type',),
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.DocumentType'),
        ),
    ]
